### PR TITLE
Moving light classes files generation to separate job

### PR DESCRIPTION
**Pull request by sellophane**

### CODE REVIEW

**Comment by zarechenskiy** [comment]
Is it somehow relevant to [KE-301](https://youtrack.jetbrains.com/issue/KE-301)?

**Comment by sellophane** [comment]
> Is it somehow relevant to [KE-301](https://youtrack.jetbrains.com/issue/KE-301)?

It is. By creating lightclasses files on `IResourceChangeEvent.PRE_REFRESH` callback, we were causing `blocked tree` exception. That's why I moved it to the separate job.

But please do not merge it yet, there is a strange problem with failing KotlinAnalyzerTest this PR somehow caused.

**Comment by sellophane** [comment]
Ok, reworked, now everything pass correctly

**Comment by zarechenskiy** [comment]
OK,  thanks!

**Pull request merged**
