### PR TITLE
Annotation support

### PR DESCRIPTION
**Pull request by wpopielarski**
Supports literals type of Byte, Integer, Short and Long (Previously only String was supported) in
annotation definition.
Adds support for `ITypeBinding` as annotation parameter in eclipse.

### CODE REVIEW

**Comment by wpopielarski** [comment]
Fixes https://youtrack.jetbrains.com/issue/KE-266

**Comment by zarechenskiy** [comment]
It'd be nice to add some tests
See this [example](https://github.com/JetBrains/kotlin-eclipse/blob/c57c30c4096e01a5fe9ab585e77baa56e2921dee/kotlin-eclipse-ui-test/testData/diagnostics/resolveConstructor.kt) how to write Kotlin-Java tests

**Comment by wpopielarski** [comment]
cool

**Comment by Kordyjan** [comment]
I added tests for both issueas fixed in this pr.

**Comment by zarechenskiy** [comment]
Thank you!

**Pull request merged**
